modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"

[[mixins]]
config = "tweaked_creative_menu-common.mixins.json"

[[mixins]]
config = "tweaked_creative_menu-neoforge.mixins.json"

[[mods]]
modId = "tweaked_creative_menu"
version = "${version}"
displayName = "Tweaked Creative Menu"
authors = "icanttellyou, GoopSwagger"
credits = ""
description = '''
A mod that improves the creative menu, including animations and sounds, which can be configured, along with data driven item groups!
'''
logoFile = "assets/tweaked_creative_menu/icon.png"

[[dependencies.tweaked_creative_menu]]
modId = "neoforge"
versionRange = "[21.0,21.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.tweaked_creative_menu]]
modId = "minecraft"
versionRange = "[1.21, 1.21.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.tweaked_creative_menu]]
modId = "yet_another_config_lib_v3"
type = "optional"
ordering = "NONE"
side = "CLIENT"